### ISSUE TITLE
Ability to reorder mission checkpoints

### ISSUE THREAD

**Issue by jj314** [Blaarkies/ksp-visual-calculator#47]
It would be useful to be able to reorder mission checkpoints by drag and dropping. Otherwise if you need to insert a checkpoint somewhere, you have to delete  and then recreate every checkpoint after that point.

**Comment by Blaarkies** [comment]
This is a great idea, I like it! 😊

Each checkpoint in the list should have a drag handle for this, just need to determine a good placement for it to function on mobile & desktop
