### ISSUE TITLE
Great tool // FYI 'Submit feedback' function not working right now

### ISSUE THREAD

**Issue by admiralnlson** [Blaarkies/ksp-visual-calculator#55]
Just bought you a coffee but I missed the comment box somehow xD Anyway.. Thanks for a great tool! It's quite impressive and very useful!

Note the "Submit feedback" is not working currently (Feb 2 20:21 CET (Paris) time).

`Could not submit feedback. Please try the GitHub link in the top-left (green) menu`

**Comment by Blaarkies** [comment]
Thanks, i appreciate it! 😊

In regards to the feedback feature: I do see 2 entries were saved today at 19:20 (that should be the default browser time). Neither entry has any details inside it, name or contact is optional, but description is required (it shouldn't even let sumbit happen without a description😅)

I'll take a look and see what's up with it, thanks!

**Comment by Blaarkies** [comment]
Fixed CORS issue that occured after the previous upgrades
