### ISSUE TITLE
Planner not discerning between Direct and Relay antennas when considering relayed connections

### ISSUE THREAD

**Issue by Poodmund** [Blaarkies/ksp-visual-calculator#60]
This issue was highlighted to me by 'Glorious Lynx' on the /r/KerbalSpaceProgram Discord server, wherein vessels were showing that they had connections back to the KSC in setups where they don't have connection in-game. This is due to the planner not discounting direct antenna power values from the vessel's power rating for relayed communications.

To replicate, set the KSC DSN level to 1. Put a relay satellite with a Communotron 88-88 Direct Antenna and a HG-5 Relay Antenna 6.5Gm from Kerbin. The expected Signal Strength here should be 56-57%, which the Planner shows correctly.

Then put a Probe satellite with a Communotron 16 Direct Antenna rendezvoused to the Relay satellite in close proximity of a few km. In the Planner, it is showing that the Probe has connection back to the KSC through the Relay satellite (incorrectly using the Communotron 88-88 to relay the communication). In game, we expect that only the HG-5 Relay Antenna is used to relay the signal, and therefore at 6.5Gm distance the HG-5 cannot communicate back to the KSC DSN1 on its own. The Probe with the Communotron 16 should have no signal and therefore no control.

I can confirm this in the screenshots below:

![image](https://github.com/Blaarkies/ksp-visual-calculator/assets/10106634/54f2365a-becb-47a8-bc38-a8a5db7f93e7)

^ Relay sat with Communotron 88-88 Direct and HG-5 Relay antenna at 6.5Gm from DSN1.

![image](https://github.com/Blaarkies/ksp-visual-calculator/assets/10106634/178f17c8-1356-4354-99c7-1e61e738eb69)

^ Probe with Communotron 16 in close proximity to Relay satellite with no connection back to the KSC DSN1. This is expected behaviour but is in conflict to what the Planner shows.

![image](https://github.com/Blaarkies/ksp-visual-calculator/assets/10106634/8a31cc78-634d-4abf-af7d-7967864c3efe)

^ Screenshot showing DSN1

![image](https://github.com/Blaarkies/ksp-visual-calculator/assets/10106634/d4e24639-bcb4-436f-bb4e-30f5dc601aca)

^ Screenshot showing 56% signal strength connection between Relay satellite and DSN1, as expected due to calculation considering both Communotron 88-88 antenna and HG-5 Relay antenna.

![image](https://github.com/Blaarkies/ksp-visual-calculator/assets/10106634/29965405-9174-4e02-8568-e5c664bd530e)

^ Screenshot of the Planner incorrectly showing the Probe satellite having connection back to the KSC DSN1 through the Relay satellite. This is due to the planner considering the Communotron 88-88 Direct antenna power contributing to the relay power of the Relay satellite vessel.

**Comment by Blaarkies** [comment]
No worries, I really appreciate my app being tested to expose any potential flaws that I missed in my tests 😊

The bad value upon starting issue is a good catch. I saw that when checking this post, but I thought it was a change in the "Difficulty setting" that modifies strength values.

It seems it is real, it probably happens in the initialization of a new universe. 
Thanks, i'll add that as a task!😄

**Comment by Blaarkies** [comment]
Resolved in #62 and #61, they changes are in the latest release if you wanted to check them out.

Here's some screenshots of various configurations:
multi-hop capability
![ksp-multi-hop](https://github.com/Blaarkies/ksp-visual-calculator/assets/21290218/ed4086b3-b226-4166-983d-179b5a790fdd)

Relay signals carry control from Kerbin to the craft
![ksp-only-full-relay-carries](https://github.com/Blaarkies/ksp-visual-calculator/assets/21290218/b770f9bd-b6db-407e-9760-a899c1759503)

single-hop example
![ksp-single-hop](https://github.com/Blaarkies/ksp-visual-calculator/assets/21290218/01f10787-9844-43bc-8e91-40e110358150)

single-hop controls itself, and craft in the first hop connection
![ksp-single-hop-no-transfer](https://github.com/Blaarkies/ksp-visual-calculator/assets/21290218/272605cf-bef7-4207-91f6-941ed1349d9b)
